<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Spotify</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
     <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link href="dashboard.css" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="<?php ?>"/>
  </head>
  <body>
  


        <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 text-success" href="#">spotify</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-nav">  
    <div class="nav-item text-nowrap">
<?php



     ?>
    </div>
   
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
        <li class="nav-item">
        <form  method="POST" action="" ><tr><td><label><?php  ?></label></td><td> 
                  </td></tr>
                </form>
             </li>
          <li class="nav-item">
        <a class="nav-link text-secondary" href="../index/refresh" ><i class="fa fa-refresh" aria-hidden="true"></i>Refresh</a>  
             </li>
             <li class="nav-item">
          <h2 class="text-success" >Spotify</h2>
             </li>
             <li class="nav-item">
            <a class="nav-link " aria-current="page" href="../index?bearer=<?php ?> ">
              <span data-feather="file"></span>
              <?php ?>
              </a>
             </li>
             <li class="nav-item">
            
             
             
             </li>
             <li class="nav-item"> 
                 <form action="../index" method="" >
                 <div class="form-group">
                 <div class="form-check">
                 <div class="form-check">
      <input type="checkbox" class="form-check-input" id="check1" name="option1" value="track" checked>
      <label class="form-check-label" for="check1">Track</label>
    </div>
    <div class="form-check">
      <input type="checkbox" class="form-check-input" id="check2" name="option2" value="album">
      <label class="form-check-label" for="check2">Album</label>
    </div>
    <div class="form-check">
      <input type="checkbox" class="form-check-input"  name="option3" value="artist" >
      <label class="form-check-label">Artist</label>
    </div>
    <div class="form-check">
      <input type="checkbox" class="form-check-input" id="check1" name="option4" value="playlist">
      <label class="form-check-label" for="check1">Playlist</label>
    </div>
    <div class="form-check">
      <input type="checkbox" class="form-check-input" id="check2" name="option5" value="show">
      <label class="form-check-label" for="check2">Show</label>
    </div>
    <div class="form-check">
      <input type="checkbox" class="form-check-input"  name="option6" value="episode" >
      <label class="form-check-label">Episode</label>
    </div>
  
   
            <input type="text" name="inputSearch" class="form-control">
            <button type="submit" class="btn btn-success mt-3">Search</button>
           </div></form>  </li>


          <li class="nav-item">
          <h6 class="h4 text-secondary">
            <a class="nav-link active text-secondary" aria-current="page" href="playlist">
              <span data-feather="user"></span>
             + New Playlist
              </a>
          </h6></li>
          <?php $playlist = $this->api->getplaylist();
                     foreach($playlist['items'] as $k =>$v){?>
          <li class="nav-item">
          <form action="../index/playlist"><button class="nav-link active text-dark border-0 bg-light " aria-current="page"name="btnplaylist" value="<?php echo $v['id']; ?>" >
                    <?php echo($v['name']); ?>
                     </button></form>
          </li>
          <?php }?>

        </ul>
        <ul class="nav flex-column mb-2">
        </ul>
      </div>
    </nav>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 ">
   
<div class="">
            <?php echo $this->getContent(); ?>
        </div>

<link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">
    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../../public/js/myscript.js"></script>  
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> 
         <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  





</body>
</html>
